name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        target: android-30
        arch: x86_64

    - name: Verify Cordova and Android versions
      run: |
        cordova -v
        cordova platforms

    - name: Add Android platform
      run: cordova platform add android@10.1.2

    - name: Clean Cordova platform
      run: cordova clean android

    - name: Build Android App
      run: cordova build android --release --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: platforms/android/app/build/outputs/apk/release/*.apk